import sys

with open('camera_test/camera_test.ino', 'r') as f:
    lines = f.readlines()

new_lines = []
skip = False
for i, line in enumerate(lines):
    if 'void captureAndPreview() {' in line:
        new_lines.append(line)
        new_lines.append('  if (ledFlashEnabled) {\n')
        new_lines.append('    digitalWrite(LED_FLASH, HIGH); if (neoFlashEnabled) neoWhiteFlash(); delay(150);\n')
        new_lines.append('    for (int i = 0; i < 2; i++) {\n')
        new_lines.append('      camera_fb_t *tfb = esp_camera_fb_get();\n')
        new_lines.append('      if (tfb) esp_camera_fb_return(tfb); esp_task_wdt_reset();\n')
        new_lines.append('    }\n')
        new_lines.append('  }\n')
        new_lines.append('  camera_fb_t* fb = esp_camera_fb_get();\n')
        new_lines.append('  if (ledFlashEnabled) digitalWrite(LED_FLASH, LOW);\n')
        new_lines.append('  if (!fb) { neoBurst(180, 0, 0, 5); return; }\n')
        new_lines.append('  neoBurst(0, 80, 255, 1);\n')
        new_lines.append('  int curRot = lcd.getRotation();\n')
        new_lines.append('  int targetRot = (curRot == 0) ? 3 : (curRot == 1) ? 2 : (curRot == 2) ? 1 : 0;\n')
        new_lines.append('  if (fb->format == PIXFORMAT_RGB565 && fb->width == DISP_W) {\n')
        new_lines.append('    uint16_t* drawBuf = (uint16_t*)fb->buf;\n')
        new_lines.append('    uint16_t* tmpRot = nullptr;\n')
        new_lines.append('    if (curRot != 3) {\n')
        new_lines.append('      tmpRot = (uint16_t*)ps_malloc(DISP_W * DISP_H * 2);\n')
        new_lines.append('      if (tmpRot) {\n')
        new_lines.append('        rotateBuffer((uint16_t*)fb->buf, tmpRot, DISP_W, DISP_H, targetRot);\n')
        new_lines.append('        drawBuf = tmpRot;\n')
        new_lines.append('      }\n')
        new_lines.append('    }\n')
        new_lines.append('    if (curRot == 0 || curRot == 2) lcd.pushImage(0, 0, DISP_H, DISP_W, drawBuf);\n')
        new_lines.append('    else lcd.pushImage(0, 0, DISP_W, DISP_H, drawBuf);\n')
        new_lines.append('    if (tmpRot) free(tmpRot);\n')
        new_lines.append('  }\n')
        new_lines.append('  drawCornerBrackets(COL_GRAY_E);\n')
        new_lines.append('  bool saved = false;\n')
        new_lines.append('  if (sdReady) {\n')
        new_lines.append('    photoCount++;\n')
        new_lines.append('    uint16_t* finalBuf = (uint16_t*)fb->buf;\n')
        new_lines.append('    uint16_t* eisBuf = nullptr;\n')
        new_lines.append('    uint16_t* rotBuf = nullptr;\n')
        new_lines.append('    int finalW = DISP_W, finalH = DISP_H;\n')
        new_lines.append('    if (fb->format == PIXFORMAT_RGB565) {\n')
        new_lines.append('      if (eisEnabled) {\n')
        new_lines.append('        eisBuf = (uint16_t*)ps_malloc(DISP_W * DISP_H * 2);\n')
        new_lines.append('        if (eisBuf) {\n')
        new_lines.append('          applyEIS((uint16_t*)fb->buf, eisBuf, DISP_W, DISP_H, g_eisOffX, g_eisOffY);\n')
        new_lines.append('          finalBuf = eisBuf;\n')
        new_lines.append('        }\n')
        new_lines.append('      }\n')
        new_lines.append('      if (curRot != 3) {\n')
        new_lines.append('        rotBuf = (uint16_t*)ps_malloc(DISP_W * DISP_H * 2);\n')
        new_lines.append('        if (rotBuf) {\n')
        new_lines.append('          rotateBuffer(finalBuf, rotBuf, DISP_W, DISP_H, targetRot);\n')
        new_lines.append('          finalBuf = rotBuf;\n')
        new_lines.append('          if (targetRot == 1 || targetRot == 3) { finalW = DISP_H; finalH = DISP_W; }\n')
        new_lines.append('        }\n')
        new_lines.append('      }\n')
        new_lines.append('    }\n')
        new_lines.append('    bool isGCrgb = (detectedSensor == PID_GC2145 && fb->format == PIXFORMAT_RGB565 && fb->width == DISP_W && fb->height == DISP_H);\n')
        new_lines.append('    if (isGCrgb && gc2145CaptureFormat == GFMT_BMP) {\n')
        new_lines.append('      char path[48]; snprintf(path, sizeof(path), "/sdcard/photo_%04d.bmp", photoCount);\n')
        new_lines.append('      char payload[32]; stegoMakePayload(payload, sizeof(payload), photoCount);\n')
        new_lines.append('      saved = saveBMP((uint8_t*)finalBuf, finalW, finalH, path, payload, (int)strlen(payload));\n')
        new_lines.append('    } else {\n')
        new_lines.append('      uint8_t* jpg = nullptr; size_t jLen = 0; bool ok = false;\n')
        new_lines.append('      if (fb->format == PIXFORMAT_RGB565) {\n')
        new_lines.append('        camera_fb_t fk = *fb; fk.buf = (uint8_t*)finalBuf; fk.width = finalW; fk.height = finalH;\n')
        new_lines.append('        int captureQ = hdCaptureEnabled ? map(hdCaptureQuality, 1, 10, 95, 50) : 85;\n')
        new_lines.append('        ok = frame2jpg(&fk, captureQ, &jpg, &jLen);\n')
        new_lines.append('      } else if (fb->format == PIXFORMAT_JPEG) { jpg = fb->buf; jLen = fb->len; ok = true; }\n')
        new_lines.append('      if (ok && jpg && jLen > 0) {\n')
        new_lines.append('        char payload[32]; stegoMakePayload(payload, sizeof(payload), photoCount);\n')
        new_lines.append('        size_t sLen = 0;\n')
        new_lines.append('        uint8_t* sBuf = stegoEmbedToJpeg(jpg, jLen, payload, (int)strlen(payload), &sLen);\n')
        new_lines.append('        if (!sBuf) { sBuf = jpg; sLen = jLen; }\n')
        new_lines.append('        size_t fLen = 0;\n')
        new_lines.append('        uint8_t* fBuf = exifInjectToJpeg(sBuf, sLen, photoCount, sensorName, &fLen);\n')
        new_lines.append('        if (!fBuf) { fBuf = sBuf; fLen = sLen; }\n')
        new_lines.append('        char path[48]; snprintf(path, sizeof(path), "/sdcard/photo_%04d.jpg", photoCount);\n')
        new_lines.append('        FILE* f = fopen(path, "wb");\n')
        new_lines.append('        if (f) { size_t w = fwrite(fBuf, 1, fLen, f); fclose(f); saved = (w == fLen); }\n')
        new_lines.append('        if (fBuf != sBuf) free(fBuf);\n')
        new_lines.append('        if (sBuf != jpg) free(sBuf);\n')
        new_lines.append('        if (fb->format != PIXFORMAT_JPEG) free(jpg);\n')
        new_lines.append('      }\n')
        new_lines.append('    }\n')
        new_lines.append('    if (eisBuf) free(eisBuf);\n')
        new_lines.append('    if (rotBuf) free(rotBuf);\n')
        new_lines.append('    if (!saved) photoCount--;\n')
        new_lines.append('  }\n')
        new_lines.append('  esp_camera_fb_return(fb);\n')
        new_lines.append('  if (saved) {\n')
        new_lines.append('    char msg[28];\n')
        new_lines.append('    bool isBmp = (detectedSensor == PID_GC2145 && gc2145CaptureFormat == GFMT_BMP);\n')
        new_lines.append('    snprintf(msg, sizeof(msg), "SAVED %s #%04d", isBmp ? "BMP" : "JPG", photoCount);\n')
        new_lines.append('    islandPush(NOTIF_OK, msg);\n')
        new_lines.append('    neoBurst(200, 150, 0, 3); if (isBmp) neoBurst(0, 80, 200, 2); else neoBurst(0, 180, 0, 2);\n')
        new_lines.append('  } else {\n')
        new_lines.append('    islandPush(NOTIF_WARN, sdReady ? "WRITE ERR" : "NO SD CARD"); neoBurst(180, 0, 0, 5);\n')
        new_lines.append('  }\n')
        new_lines.append('  fpsLastTime = millis(); fpsFrameCount = 0;\n')
        new_lines.append('  resetAllButtons();\n')
        new_lines.append('}\n')
        skip = True
        continue

    if skip:
        if 'void applySensorSettings(sensor_t *s,uint16_t pid){' in line:
            skip = False
        else:
            continue

    new_lines.append(line)

with open('camera_test/camera_test.ino', 'w') as f:
    f.writelines(new_lines)
