name: Build ESP32

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32s3
          platforms: |
            - name: "esp32:esp32"
              version: "2.0.17"
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - name: LovyanGFX
          sketch-paths: |
            - camera_test/camera_test.ino
          enable-deltas-report: 'false'
          cli-compile-flags: |
            - --output-dir
            - ./output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-bin
          path: output/*.bin
